### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by HareeshBahuleyan** [ygorg/KPTimes#4]
Hi,
Thanks for making this dataset available. Would it be possible to provide the full `jsonl` files, instead of having to download the html files one-by-one?

I tried downloading the datasets using the scripts. However, the news articles for certain links have been removed by the publisher and hence are broken links. For example:

1. https://www.japantimes.co.jp/news/2014/10/05/asia-pacific/offbeat-asia-pacific/south-korea-rumor-crackdown-jolts-social-media-users
2. https://www.japantimes.co.jp/news/2014/10/20/asia-pacific/offbeat-asia-pacific/china-zoo-bear-bites-boys-arm-off
 
- With JPTimes test set, there were 1576 missing articles.

**Comment by ygorg** [comment]
Hi,
I added links to download the processed data in the readme !
Thank you for reporting the broken links. I updated `test_JPTime.url.filelist` with `web.archive` links (but there are still 12 broken links, I will somehow make them available).

**Comment by HareeshBahuleyan** [comment]
Hi @ygorg 
Thanks for providing links to the processed data.

**Comment by lujiaying** [comment]
I encountered the same issue. And I found that there are some articles expired in `JPTime`.

For example, https://www.japantimes.co.jp/news/2016/12/29/world/politics-diplomacy-world/native-americans-hail-republicans-rail-obamas-monument-picks-utah-nevada is not valid on the website.

**Comment by ygorg** [comment]
Hi @lujiaying,
`KPTimes.test.jsonl` contains the articles from the NewYorkTime and the JapanTime. You can tell from which website the document were extracted by checking their ids (it either begins with `ny`for NewYorkTime or `jp` for JapanTime).
Hope this clarifies some things.

**Comment by lujiaying** [comment]
Hi @ygorg,
Thank you very much for the explanation! Sorry that I didn't check the id/URL carefully. 
Now everything is available for further investigation.

Best,
Jiaying
